### ISSUE TITLE
Omit nullable String arguments instead of converting them to "null"

### ISSUE THREAD

**Issue by ChristianOrgler** [levinzonr/compose-safe-routing#14]
When specifying a navigation argument as a String type, optional the parameter is still appended with a string "null" instead of being ommitted in the route.

Is this expected or would this be an enhancement to work on?

**Comment by ChristianOrgler** [comment]
hmm so if I would expect that an optional argument should not be set with "null" I would need to change this:

```RouteArg(name = "someId", type = String::class, isOptional = true, isNullable = true)```

to this?
```RouteArg(name = "someId", type = String::class, isOptional = true)```

**Comment by ChristianOrgler** [comment]
Can you confirm that when you say `null` will be used you mean it as `String` not as being null correct?

I'd like to achieve to have an `optional` route argument that is either `null` or has a value passed into the route. Not being `null` as String value. Is this possible?

**Comment by levinzonr** [comment]
@ChristianOrgler This thing you posted earlier does exactly that
`RouteArg(name = "someId", type = String::class, isOptional = true, isNullable = true)` 

In args, you would receive either the arg you have passed or `null` 
If thats not the case thats probably a bug on my side :)

I see there is some confusion with `null` and "null". Do you receive the "null"  text instead of `null`?

**Comment by ChristianOrgler** [comment]
Correct I receive `null` as String - because in `RouteActions` f.e. it simply does the following: 

```
public fun toMyRoute(myArgument: String? = null): String =
      "MyRoute?myArgument=$myArgument"
```

when the `RouteArg` looks like this:
```
RouteArg(name = "myArgument", type = String::class, isOptional = true, isNullable = true)
```

**Comment by levinzonr** [comment]
Ok, I understand the issue now, and it is definitely a bug on my side 👍 
 I'll introduce the hotfix later today
Thanks for bringing up @ChristianOrgler 🙂

**Comment by ChristianOrgler** [comment]
Thanks for the quick responses, let me know if I can help in any way :)

**Comment by levinzonr** [comment]
Hey @ChristianOrgler 🙂 
2.3.1 is now available on Jitpack, feel free to re-open this issue in case something is not right

And thanks for contributing 👍

**Comment by ChristianOrgler** [comment]
Fix confirmed :+1:
