### ISSUE TITLE
Route not generated for composable with a "Dp" parameter

### ISSUE THREAD

**Issue by Ezard** [levinzonr/compose-safe-routing#15]
No route was generated for my composable when it looked like this:
```kotlin
@Route(name = "profile")
@Composable
fun ProfileScreen(bottompadding: Dp) {}
```

Removing the "Dp" (`androidx.compose.ui.unit.Dp`) parameter meant that the route was correctly generated

I ended up swapping out that parameter for a `PaddingValues` parameter, and that works fine

**Comment by levinzonr** [comment]
Hey @Ezard !
What version of the library are you using?

**Comment by Ezard** [comment]
Thanks for the quick reply @levinzonr!

I'm using version `2.3.1` - sorry, I should've mentioned that in my original message

**Comment by levinzonr** [comment]
Hey @Ezard , I apologize for the delay
It looks the issue is related to `kapt` and how it works with inline classes in general.
From my quick search I haven't found any solutions to that, but using `ksp` instead of `kapt` might solve the issue
I will create another issue for this support

**Comment by Ezard** [comment]
No worries at all @levinzonr, thanks for getting back to me

Thanks for your work on this library btw, it's super useful!

Happy for you to close this issue in favour of the KSP one if you want :)

**Comment by levinzonr** [comment]
@Ezard I think your issue should be solved now when using KSP instead of kapt :)
Sorry for the long wait
