### ISSUE TITLE
RouteAction for BottomSheet with argument 

### ISSUE THREAD

**Issue by hidayat05** [levinzonr/compose-safe-routing#22]
sample generated RouteActions

```
object RoutesActions {
  /**
   * Builds an action to "transaction_status" route
   */
  fun toTransaction_status(status: String): String = "transaction_status/$status"  --> should transaction_status?status={status}
  
}
```

there should be a differentiator for Route bottomsheet.
Thanks.

**Comment by levinzonr** [comment]
Hey @hidayat05 !
If I understood correctly, you want to use optional argument in you route action
To do that you need to specify it inside the annotation like so

```
@Route(
 name = "route",
args = [RouteArg("id", isOptional = true, defaultValue = "default_id"
)
```
If that's not what you are asking, can you clarify a bit more and show how did you setup your navigation :)
Thanks!
